# Google App Engine configuration
# Project ID: falken-drinks
# Project number: 257330941577
# https://cloud.google.com/appengine/docs/standard/python3/runtime
runtime: python311
service: default
instance_class: F1

# Entrypoint: gunicorn serving the Flask app factory
# https://docs.gunicorn.org/en/stable/run.html
entrypoint: gunicorn -b :$PORT 'falken_drinks.app:create_app()'

env_variables:
  LEVEL_LOG: "INFO, WARNING, ERROR"
  CONFIG_MODE: "production"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

includes:
- credentials.yaml